{% set python_min = '3.10' %}
{% set name = "intake-thredds" %}
{% set version = "2024.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake-thredds-{{ version }}.tar.gz
  sha256: 282fe789cbee0f9060180ef1507729e09b60686cc7a9dd71f75a9206b74445c8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm
  run:
    - aiohttp >=3.7
    - fsspec >=0.8.5
    - h5netcdf >=0.8.1
    - intake >=0.6.6,<2
    - intake-xarray >=0.3
    - pydap
    - python >={{ python_min }}
    - siphon
    - tqdm

test:
  imports:
    - intake_thredds
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake/intake-thredds
  summary: Intake interface to THREDDS data catalogs
  description: |
    Intake interface to THREDDS data catalogs
  doc_url: https://intake-thredds.readthedocs.io/en/latest/
  dev_url: https://github.com/intake/intake-thredds
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - aaronspring
