{% set name = "intake-thredds" %}
{% set version = "2025.2.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 37bc5a9ac78c9168b3afd63d9beec8021b1dd60bcd3e951de51b17b6dedcba6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=45
    - setuptools_scm
  run:
    - aiohttp >=3.7
    - fsspec >=0.8.5
    - h5netcdf >=0.8.1
    - intake >2
    - intake-xarray
    - pydap
    - python >=3.10
    - siphon
    - tqdm
    - setuptools >=45 # should be removed since it is deprecated: https://setuptools.pypa.io/en/latest/pkg_resources.html

test:
  imports:
    - intake_thredds
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-thredds
  summary: Intake interface to THREDDS data catalogs
  description: |
    Intake interface to THREDDS data catalogs
  doc_url: https://intake-thredds.readthedocs.io/en/latest/
  dev_url: https://github.com/intake/intake-thredds
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - andersy005
    - aaronspring
