{% set name = "intake-thredds" %}
{% set version = "2021.6.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-thredds-{{ version }}.tar.gz
  sha256: 4fe1f8f598d75fb438b64a53cc206ff603399c6264cc05e095c11184a587ad04

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - aiohttp >=3.7
    - fsspec >=0.8.5
    - h5netcdf >=0.8.1
    - intake >=0.6.0
    - intake-xarray >=0.3
    - pydap
    - python >=3.7
    - siphon
    - tqdm

test:
  imports:
    - intake_thredds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NCAR/intake-thredds
  summary: Intake interface to THREDDS data catalogs.
  dev_url: https://github.com/NCAR/intake-thredds
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - aaronspring
